In [67]:
import tensorflow as tf

In [68]:
# train data
x_train = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_train = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [69]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 3])

In [70]:
W = tf.Variable(tf.random_normal([4, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

In [72]:
# hypothesis
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
scores = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(scores)

In [73]:
# cost/loss function
# cross entropy
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [74]:
# minimize cost
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

In [75]:
# accuracy computation
predicted = tf.argmax(hypothesis, 1)
real = tf.argmax(Y, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, real), dtype=tf.float32))

In [76]:
# prepare session
session = tf.Session()
session.run(tf.global_variables_initializer())

In [79]:
# fit the model
for step in range(10001):
    h_val, c_val, _, p_val, a_val = session.run([hypothesis, cost, train, predicted, accuracy],
                                  feed_dict={X: x_train, Y: y_train})
    if step % 500 == 0:
        print(step, h_val, c_val, p_val, a_val)

s1 = session.run(hypothesis, feed_dict={X: [[11, 1, 2, 9]]})
print("\n==>", session.run(tf.argmax(s1, 1)))

s2 = session.run(hypothesis, feed_dict={X: [[1, 3, 2, 0]]})
print("\n==>", session.run(tf.argmax(s2, 1)))

all = session.run(hypothesis, feed_dict={X:[[10, 9, 8, 7],
                                            [7, 8, 10, 1],
                                            [1, 5, 10, 2]]})
print("\n==>", session.run(tf.argmax(all, 1)))

0 [[1.64498852e-05 2.34498386e-03 9.97638583e-01]
 [1.81970967e-03 1.08959645e-01 8.89220655e-01]
 [2.39907081e-06 2.15765953e-01 7.84231603e-01]
 [1.76993144e-05 8.02659810e-01 1.97322533e-01]
 [3.36227566e-01 6.47456706e-01 1.63157173e-02]
 [1.76752880e-01 8.23242247e-01 4.92914251e-06]
 [6.96737289e-01 3.03223342e-01 3.93491355e-05]
 [8.75851691e-01 1.24147221e-01 1.03141201e-06]] 0.21322034 [2 2 2 1 1 1 0 0] 1.0
500 [[1.36021590e-05 2.14114599e-03 9.97845292e-01]
 [1.72748475e-03 1.06508374e-01 8.91764164e-01]
 [1.89056595e-06 2.11223632e-01 7.88774490e-01]
 [1.51594140e-05 8.06900382e-01 1.93084404e-01]
 [3.29866707e-01 6.54220819e-01 1.59124602e-02]
 [1.73474416e-01 8.26521158e-01 4.45497017e-06]
 [7.00422406e-01 2.99542218e-01 3.54215153e-05]
 [8.79945338e-01 1.20053835e-01 8.78044830e-07]] 0.20841847 [2 2 2 1 1 1 0 0] 1.0
1000 [[1.1295235e-05 1.9590177e-03 9.9802965e-01]
 [1.6425070e-03 1.0415896e-01 8.9419854e-01]
 [1.4974145e-06 2.0685509e-01 7.9314339e-01]
 [1.3031419e-05 8.