In [214]:
import tensorflow as tf

# for reproducibility
tf.set_random_seed(777) 

In [215]:
x_train = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_train = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [216]:
# Placeholder
X = tf.placeholder("float", shape=[None, 3])
Y = tf.placeholder("float", shape=[None, 3])

In [217]:
# Variables
W = tf.Variable(tf.random_normal([3, 3]), name='weight')
b = tf.Variable(tf.random_normal([3]), name='bias')

In [218]:
# Hypothesis
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

In [276]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

In [277]:
# Minimize
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1055)
train = optimizer.minimize(cost)

In [278]:
# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [279]:
# Prepare Session
session = tf.Session()

# Initialize TensorFlow variables
session.run(tf.global_variables_initializer())

In [280]:
# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [281]:
for step in range(201):
    cost_val, W_val, _ = session.run([cost, W, train],
                                     feed_dict={X: x_train, Y: y_train})
    if step % 20 == 0:
        print(step, cost_val, W_val)
        
print("\nPrediction = ", session.run(prediction, feed_dict={X: x_test}))
print("\nAccuracy = ", session.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 2.8514025 [[ 0.54849875  0.2774999   0.61170375]
 [ 0.2987189   0.9435638  -0.33494022]
 [-0.6164946  -1.2089976  -0.3119737 ]]
20 0.9995849 [[ 0.32284614  0.25428337  0.86057264]
 [ 0.33336517  0.58708847 -0.01311107]
 [-0.62107444 -0.8617519  -0.65463936]]
40 0.8402449 [[ 0.1337651   0.2421773   1.0617596 ]
 [ 0.38110104  0.38669676  0.13954483]
 [-0.59962827 -0.6480586  -0.88977903]]
60 0.7649796 [[-0.02438189  0.23063634  1.2314475 ]
 [ 0.4090403   0.2926211   0.20568135]
 [-0.56466305 -0.5442459  -1.028557  ]]
80 0.7194795 [[-0.1607251   0.22058973  1.3778373 ]
 [ 0.42414886  0.2535111   0.22968277]
 [-0.5244123  -0.49677855 -1.1162747 ]]
100 0.6864561 [[-0.28218573  0.21311793  1.5067698 ]
 [ 0.43339944  0.23951152  0.23443183]
 [-0.48390126 -0.47617337 -1.1773908 ]]
120 0.6602715 [[-0.3929928   0.20844415  1.6222508 ]
 [ 0.4402845   0.236411    0.23064739]
 [-0.44467592 -0.46870545 -1.2240843 ]]
140 0.63871515 [[-0.4957305   0.20634203  1.7270904 ]
 [ 0.44645     0.2374509   0

In [ ]:

0.08 => 0.59063303
0.09 => 0.5778148
0.1  => 0.56607723
0.101=> 0.56495595
0.102=> 0.56384355
0.105=> 0.56200933
0.11 => 0.59834707
0.2  => 1.2767676