In [63]:
import tensorflow as tf

In [64]:
file_name_queue = tf.train.string_input_producer(['../datas/data-01-test-score.csv'],
                                                shuffle=False, name='filename_queue')

In [65]:
reader = tf.TextLineReader()
key, value = reader.read(file_name_queue)

In [66]:
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

In [67]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

In [68]:
# placeholder
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [69]:
# Variables
W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [70]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [71]:
# cost
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [72]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [73]:
# prepare session
session = tf.Session()
session.run(tf.global_variables_initializer())

In [74]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=session, coord=coord)

In [76]:
for step in range(10001):
    x_batch, y_batch = session.run([train_x_batch, train_y_batch])
    cost_val, hypothesis_val, _ = session.run([cost, hypothesis, train],
                                              feed_dict={X: x_batch, Y: y_batch})
    if step % 100 == 0:
        print("x_batch: ", x_batch, "\ny_batch: ", y_batch)
        print(step, "Cost: ", cost_val, "\nPrediction: ", hypothesis_val)

x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
0 Cost:  5.204899 
Prediction:  [[143.99268]
 [142.83105]
 [186.15019]
 [153.1437 ]
 [151.42722]
 [188.44388]
 [144.65273]
 [181.05168]
 [177.1681 ]
 [158.71188]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
100 Cost:  5.207483 
Prediction:  [[143.99376]
 [142.8304 ]
 [186.14815]
 [153.13954]
 [151.43091]
 [188.44264]
 [144.64537]
 [181.05899]
 [177.1667 ]
 [158.71144]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_ba

x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
2000 Cost:  5.2487316 
Prediction:  [[144.00955]
 [142.81787]
 [186.11998]
 [153.08046]
 [151.48499]
 [188.42279]
 [144.53864]
 [181.16805]
 [177.14896]
 [158.7077 ]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
2100 Cost:  5.250516 
Prediction:  [[144.01016]
 [142.81725]
 [186.11894]
 [153.07819]
 [151.48714]
 [188.42192]
 [144.53441]
 [181.17245]
 [177.14836]
 [158.70767]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 

x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
4000 Cost:  5.277768 
Prediction:  [[144.01932]
 [142.80713]
 [186.10458]
 [153.04565]
 [151.51886]
 [188.40875]
 [144.4729 ]
 [181.23862]
 [177.14085]
 [158.70837]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
4100 Cost:  5.2788987 
Prediction:  [[144.01967]
 [142.80669]
 [186.10403]
 [153.04439]
 [151.52014]
 [188.4082 ]
 [144.47046]
 [181.2413 ]
 [177.1406 ]
 [158.70845]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 

x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
6000 Cost:  5.2959332 
Prediction:  [[144.02492]
 [142.79942]
 [186.09648]
 [153.02585]
 [151.5389 ]
 [188.39989]
 [144.43428]
 [181.28151]
 [177.13737]
 [158.71   ]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
6100 Cost:  5.2966127 
Prediction:  [[144.02512]
 [142.79909]
 [186.09619]
 [153.0251 ]
 [151.53963]
 [188.39954]
 [144.43282]
 [181.28314]
 [177.13725]
 [158.71007]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]]

x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
8000 Cost:  5.3069086 
Prediction:  [[144.02808]
 [142.79413]
 [186.09218]
 [153.01427]
 [151.55075]
 [188.39452]
 [144.41118]
 [181.3077 ]
 [177.1359 ]
 [158.71141]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
8100 Cost:  5.3073087 
Prediction:  [[144.02818]
 [142.7939 ]
 [186.09203]
 [153.01382]
 [151.55118]
 [188.3943 ]
 [144.4103 ]
 [181.3087 ]
 [177.13585]
 [158.71146]]
x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]]

x_batch:  [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch:  [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
10000 Cost:  5.3133354 
Prediction:  [[144.02975]
 [142.79053]
 [186.08994]
 [153.00737]
 [151.55772]
 [188.39134]
 [144.3972 ]
 [181.32372]
 [177.13533]
 [158.7124 ]]


In [77]:
coord.request_stop()
coord.join(threads)