In [79]:
import tensorflow as tf
import numpy as np

In [80]:
# load csv file
datas = np.loadtxt('../datas/data-06-zoo.csv', delimiter=',', dtype=np.float32)

print(datas.shape)

(101, 17)


In [103]:
# x feature, y label
x_train = datas[:, 0:-1]
y_train = datas[:, [-1]]

print("x_train => ", x_train.shape, x_train.ndim)
print(x_train[0:5])
print("y_train => ", y_train.shape, y_train.ndim)
print(y_train[0:5])

x_train =>  (101, 16) 2
[[1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 4. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 4. 1. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 4. 0. 0. 1.]
 [1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 4. 1. 0. 1.]]
y_train =>  (101, 1) 2
[[0.]
 [0.]
 [3.]
 [0.]
 [0.]]


In [104]:
# Placeholder
X = tf.placeholder(tf.float32, shape=[None, 16])
Y = tf.placeholder(tf.int32, shape=[None, 1])

In [105]:
# Variables
W = tf.Variable(tf.random_normal([16,7]), name='weight')
b = tf.Variable(tf.random_normal([7]), name='bias') # 0 ~ 6

In [107]:
Y_one_hot = tf.one_hot(Y, 7)
print("one_hot: ", Y_one_hot)
Y_one_hot = tf.reshape(Y_one_hot, [-1, 7])
print("reshape: ", Y_one_hot)

one_hot:  Tensor("one_hot_16:0", shape=(?, 1, 7), dtype=float32)
reshape:  Tensor("Reshape_12:0", shape=(?, 7), dtype=float32)


In [108]:
# Hypothesis
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

In [109]:
# Cost
# Cross entropy cost/loss
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits, labels=Y_one_hot)
cost = tf.reduce_mean(cost_i)

In [110]:
# Minimize Cost
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)

In [111]:
# Accuracy computation
prediction = tf.argmax(hypothesis, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, tf.argmax(Y_one_hot, 1)), dtype=tf.float32))

In [112]:
# Prepare session
session = tf.Session()
session.run(tf.global_variables_initializer())

In [113]:
# Fit the model
for step in range(10001):
    session.run(train, feed_dict={X: x_train, Y: y_train})
    if step % 500 == 0:
        c_val, a_val = session.run([cost, accuracy], feed_dict={X: x_train, Y: y_train})
        print("Step={:5}\tCost={:.3f}\tAccuray={:.2%}".format(step, c_val, a_val))

p_val = session.run(prediction, feed_dict={X: x_train, Y: y_train})
for p, y in zip(p_val, y_train.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

Step=    0	Cost=4.291	Accuray=7.92%
Step=  500	Cost=0.996	Accuray=65.35%
Step= 1000	Cost=0.688	Accuray=79.21%
Step= 1500	Cost=0.537	Accuray=81.19%
Step= 2000	Cost=0.448	Accuray=83.17%
Step= 2500	Cost=0.385	Accuray=90.10%
Step= 3000	Cost=0.338	Accuray=91.09%
Step= 3500	Cost=0.300	Accuray=91.09%
Step= 4000	Cost=0.269	Accuray=92.08%
Step= 4500	Cost=0.244	Accuray=93.07%
Step= 5000	Cost=0.223	Accuray=93.07%
Step= 5500	Cost=0.205	Accuray=96.04%
Step= 6000	Cost=0.190	Accuray=96.04%
Step= 6500	Cost=0.177	Accuray=96.04%
Step= 7000	Cost=0.165	Accuray=96.04%
Step= 7500	Cost=0.155	Accuray=96.04%
Step= 8000	Cost=0.146	Accuray=96.04%
Step= 8500	Cost=0.138	Accuray=98.02%
Step= 9000	Cost=0.130	Accuray=98.02%
Step= 9500	Cost=0.124	Accuray=98.02%
Step=10000	Cost=0.118	Accuray=98.02%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] 