In [16]:
import tensorflow as tf
import numpy as np
import pprint

In [18]:
pp = pprint.PrettyPrinter(indent=4)
session = tf.InteractiveSession()

# Simple Array

In [19]:
tarray = np.array([0., 1., 2., 3., 4., 5., 6.])
print(tarray)
print(tarray.ndim)
print(tarray.shape)
print(tarray[0])
print(tarray[-1])
print(tarray[0:5])
print(tarray[:5])
print(tarray[0:])
print(tarray[:-1])
print(tarray[-1:])
print(tarray[:2])
print(tarray[2:])

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
0.0
6.0
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4. 5. 6.]
[0. 1. 2. 3. 4. 5.]
[6.]
[0. 1.]
[2. 3. 4. 5. 6.]


# 2D Array

In [30]:
tarray = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

pp.pprint(tarray)
print(tarray.ndim)
print(tarray.shape)
pp.pprint(tarray[:])
pp.pprint(tarray[-1:])
pp.pprint(tarray[:1])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
array([[10., 11., 12.]])
array([[1., 2., 3.]])


# Shape, Rank, Axis

In [36]:
t = tf.constant([1, 2, 3, 4])
print(t.shape)

tf.shape(t).eval()

(4,)


array([4], dtype=int32)

In [39]:
t = tf.constant([[1, 2], 
                 [3, 4]])
print(t.shape)
tf.shape(t).eval()

(2, 2)


array([2, 2], dtype=int32)

In [42]:
t = tf.constant([[[1,2,3], [4,5,6], [7,8,9]], [[10,11,12], [13,14,15], [16,17,18]]])
print(t.shape)
tf.shape(t).eval()

(2, 3, 3)


array([2, 3, 3], dtype=int32)

# Matmul vs Multiply

In [58]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[10.], [11.]])
print(matrix1.shape, matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

(2, 2) (2, 1)


array([[32.],
       [74.]], dtype=float32)

In [59]:
(matrix1 * matrix2).eval()

array([[10., 20.],
       [33., 44.]], dtype=float32)

# Broadcasting

In [62]:
matrix1 = tf.constant([[1,2], [3,4]])
matrix2 = tf.constant([3])
## shape이 안 맞아서 matrix muliply를 할 수 없는데
# tf.matmul(matrix1, matrix2).eval()
## shape을 강제로 맞춰주는게 broadcasting이다.
## [[3, 3]]로 shape를 강제로 맞춰줌.
(matrix1 + matrix2).eval()

array([[4, 5],
       [6, 7]], dtype=int32)

# Reduce mean

In [64]:
# 결과가 1.5가 아니고, 1인 건 integer라서 임. type도 고려해야 한다.
tf.reduce_mean([1, 2], axis=0).eval()

1

In [74]:
x = tf.constant([[1., 2.],
                 [3., 4.]])

tf.reduce_mean(x).eval()

2.5

In [75]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [76]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [77]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

# Reduce Sum

In [78]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [82]:
tf.reduce_sum(x, axis=1).eval()
# axis = 1 == axis = -1
# tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [84]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

# Argmax
#### 가장 큰 값의 위치

In [86]:
x = [[1, 2, 0],
     [2, 0, 1]]
tf.argmax(x, axis=0).eval()

array([1, 0, 1])

In [87]:
tf.argmax(x, axis=1).eval()

array([1, 0])

In [88]:
tf.argmax(x, axis=-1).eval()

array([1, 0])

# Reshape

In [90]:
t = np.array([[[0,1,2],
               [3,4,5]],
             [[6,7,8],
              [9,10,11]]])

print(t.ndim, t.shape)

3 (2, 2, 3)


In [91]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [92]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [94]:
x = [[1], [2], [3]]

tf.squeeze(x).eval()

array([1, 2, 3], dtype=int32)

In [95]:
x = [1, 2, 3]

tf.expand_dims(x, 1).eval()

array([[1],
       [2],
       [3]], dtype=int32)

# One-hot

In [97]:
x = [[0], [1], [2], [3]]

tf.one_hot(x, depth=4).eval()

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[0., 0., 0., 1.]]], dtype=float32)

In [99]:
# one-hot은 rank를 1개 늘려서 늘어난게 싫으면 줄이기 위해서 reshape 활용함.
tf.reshape(tf.one_hot(x, depth=4), shape=[-1, 4]).eval()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

# Casting

In [106]:
tf.cast([1.5, 0.9, 2.3,], dtype=tf.int32).eval()

array([1, 0, 2], dtype=int32)

In [108]:
tf.cast([True, False, True == False, 1.4, 0], dtype=tf.int32).eval()

array([1, 0, 0, 1, 0], dtype=int32)

# Stack

In [109]:
x = [1, 2]
y = [3, 4]
z = [5, 6]

tf.stack([x, y, z]).eval()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [110]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [111]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)

In [112]:
tf.stack([x, y, z], axis=-1).eval()

array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)

# Ones and Zero like

In [118]:
x = [[1, 2], [3,4]]

tf.ones_like(x).eval()

array([[1, 1],
       [1, 1]], dtype=int32)

In [119]:
tf.zeros_like(x).eval()

array([[0, 0],
       [0, 0]], dtype=int32)

# Zip

In [121]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [123]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7,8,9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
