In [26]:
import tensorflow as tf
import numpy as np

In [27]:
tf.set_random_seed(777)

In [28]:
data = np.loadtxt('../datas/data-01-test-score.csv', delimiter = ',', dtype = np.float32)

In [29]:
x_train = data[:, 0: -1]
y_train = data[:, [-1]]

print(x_train.shape, x_train, len(x_train))
print(y_train.shape, y_train, len(y_train))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 25


In [30]:
# placeholder
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

In [31]:
# Variables
W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [32]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [33]:
# Cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [34]:
# minimize cost
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [35]:
# prepare session
session = tf.Session()
session.run(tf.global_variables_initializer())

In [37]:
# fit
for step in range(5001):
    hypothesis_val, cost_val, _ = session.run([hypothesis, cost, train],
                                              feed_dict = {X: x_train, Y: y_train})
    if step % 200 == 0:
        print(step, "Cost: ", cost_val, "\n Prediction: ", hypothesis_val)
        
print("your score will be ", session.run(hypothesis,
                                         feed_dict={X: [[100, 90, 95]]}))
print("other score will be ", session.run(hypothesis,
                                          feed_dict={X: [[100, 90, 95], [60, 80, 90]]}))

0 Cost:  6.623803 
 Prediction:  [[153.78397 ]
 [184.0553  ]
 [181.61688 ]
 [198.84117 ]
 [139.42838 ]
 [104.544106]
 [150.78915 ]
 [114.48197 ]
 [173.2286  ]
 [162.84955 ]
 [143.97278 ]
 [142.09085 ]
 [186.48224 ]
 [153.4968  ]
 [151.50061 ]
 [187.8709  ]
 [144.67227 ]
 [181.70334 ]
 [177.73819 ]
 [159.36078 ]
 [176.24677 ]
 [173.81384 ]
 [167.80676 ]
 [152.41818 ]
 [190.32071 ]]
200 Cost:  6.558204 
 Prediction:  [[153.72337]
 [184.08757]
 [181.59285]
 [198.83595]
 [139.46172]
 [104.61315]
 [150.78679]
 [114.47932]
 [173.30867]
 [162.9793 ]
 [143.9803 ]
 [142.1526 ]
 [186.43788]
 [153.43706]
 [151.51622]
 [187.91386]
 [144.62257]
 [181.68944]
 [177.67638]
 [159.29787]
 [176.25166]
 [173.85777]
 [167.79655]
 [152.31105]
 [190.32784]]
400 Cost:  6.5028706 
 Prediction:  [[153.66759]
 [184.11751]
 [181.57083]
 [198.83102]
 [139.49287]
 [104.67666]
 [150.78407]
 [114.47584]
 [173.38232]
 [163.09819]
 [143.98705]
 [142.20932]
 [186.39743]
 [153.38274]
 [151.5301 ]
 [187.95341]
 [144.57784

4800 Cost:  6.2051616 
 Prediction:  [[153.11755]
 [184.43616]
 [181.36726]
 [198.77322]
 [139.8424 ]
 [105.29816]
 [150.70682]
 [114.34288]
 [174.10574]
 [164.21567]
 [144.03636]
 [142.75194]
 [186.03802]
 [152.91562]
 [151.61665]
 [188.34186]
 [144.23819]
 [181.46095]
 [177.10028]
 [158.69815]
 [176.2489 ]
 [174.29305]
 [167.65053]
 [151.30515]
 [190.43515]]
5000 Cost:  6.2037163 
 Prediction:  [[153.1086  ]
 [184.44212 ]
 [181.36441 ]
 [198.77199 ]
 [139.84949 ]
 [105.30807 ]
 [150.70386 ]
 [114.337395]
 [174.11743 ]
 [164.23204 ]
 [144.03658 ]
 [142.76021 ]
 [186.03348 ]
 [152.9103  ]
 [151.6164  ]
 [188.34814 ]
 [144.23604 ]
 [181.45479 ]
 [177.09308 ]
 [158.69022 ]
 [176.24725 ]
 [174.29935 ]
 [167.647   ]
 [151.29233 ]
 [190.43787 ]]
your score will be  [[190.15686]]
other score will be  [[190.15686]
 [165.48059]]
